version: "3"
services:
  server:
    build:
      context: ./server/Movies/src
      dockerfile: Dockerfile
    ports:
      - 3000:80
      - 3001:443
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on: 
          - server

    
