#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["/Movies.API/Movies.API.csproj", "/Movies.API/"]
COPY ["/Movies.Application/Movies.Application.csproj", "/Movies.Application/"]
COPY ["/Movies.Domain/Movies.Domain.csproj", "/Movies.Domain/"]
COPY ["/Movies.Infrastructure/Movies.Infrastructure.csproj", "/Movies.Infrastructure/"]
RUN dotnet restore "/Movies.API/Movies.API.csproj"
COPY . .
WORKDIR "/src/Movies.API"
RUN dotnet build "Movies.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Movies.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Movies.API.dll"]